name: Android CI

on:
  workflow_dispatch: # To trigger manual build
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease --no-daemon

    - name: Publish Apk
      uses: actions/upload-artifact@v3
      with:
        name: Notes.apk
        path: app/build/outputs/apk/release/app-release.apk
